export const ADD_PRODUCT_TO_CART = 'CART/ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'CART/REMOVE_PRODUCT_FROM_CART';
export const LOAD_CATEGORIES_LIST = 'CATEGORIES/LOAD_CATEGORIES_LIST';
export const SELECT_CATEGORY = 'CATEGORIES/SELECT_CATEGORY';
export const LOAD_PRODUCTS = 'PRODUCTS/LOAD_PRODUCTS';
export const SELECT_PRODUCT = 'PRODUCTS/SELECT_PRODUCT';
